feature: 템플릿 생성 API 구현
lane4company/lane4-notification-api pull request #3
Opened 2023-09-18 01:11 UTC by lane4-ellie

---

### PR Type ✔️

- [X] Feature - 기능 개발
- [ ] Fix - 버그 수정
- [ ] Code Style - 코드 스타일
- [ ] Refactoring - 리팩토링
- [ ] Document - 문서
- [ ] Others - 빌드, 배포 및 의존성 등 기타사항

---

### Summary(요약) ⭐

템플릿 생성 API 구현

---

### Describe your changes(상세) 🧾

- 템플릿을 생성하는 DTO와 컨트롤러, 서비스를 추가했습니다.
- `create` 메서드를 정의한 Template 인터페이스를 추가했습니다.
  - `create`: 템플릿 생성 DTO와 엔티티를 기반으로 템플릿을 생성하는 메서드
-  Provider type, Template를 저장하는 Task 클래스를 추가했습니다.
- Task type과  Task를 매핑하는 매퍼를 추가했습니다.
  - Task type으로 Task를 찾을 수 있는 메서드를 구현했습니다.
  - Task가 없는 경우에 대한 예외 처리를 했습니다.
- `find` 메서드를 정의한 FindEntityService 인터페이스를 추가했습니다.
  - `find`: 요청 DTO의 `keyIndex`를 기반으로 엔티티를 찾는 메서드
  - ID가 아닌 다른 필드일 수 있으므로, 메서드명을 `find`로 지정했습니다.
  - 추후 도메인별로 Find{도메인명}EntityService를 생성하고, `find` 함수에서 필요한 필드에 맞는 where 절을 걸어 구현할 수 있습니다.
 

---

### Issue Number or Link 🔗

---

### Reference

---

[//]: # (PR 타이틀은 "Type: 타이틀" 형식으로 작성)

[//]: # (Summary의 경우 작업의 전반적인 내용을 함축 및 요약하여 작성)

[//]: # (Describe your changes의 경우 무슨 상황에서 왜 이러한 변경이 필요했고, 어떻게 작업햇는지 상세 기술)

[//]: # (Issue의 경우 추후 필요시 사용)

[//]: # (Reference의 경우 해당 변경점에서 중요하게 찾아본 자료가 있거나, 이해하는데 도움이 되는 내용을 포함)

2023-09-18 04:30 UTC, lane4-asher requested changes

2023-09-18 04:39 UTC, lane4-ellie commented on src/domains/template/application/task.template.mapper.ts
> +  constructor() {}
추후 task가 추가될 것을 예상하여 FindEntityService 구현체를 생성자로 주입받으려고 추가했습니다.
다음에는 의미없는 생성자는 지양하고 생성자가 필요한 로직에서 작성하도록 하겠습니다.

2023-09-18 04:50 UTC, lane4-ellie commented on src/domains/template/dto/create.template.request.ts
> +}
옵셔널 필드가 DB에 들어갈 때 null이 들어가는 것을 명시하려는 의도였습니다.
그리고 개인적으로 (경험이 많지는 않지만..🥲) api에 요청 보낼 때 필드에 값이 없다고 해서 필드 자체를 누락시키는 경우보다는 null 값을 그대로 보내는 경우가 많다고 생각했습니다.
해당 필드를 필수로 두어 값이 없는 경우에는 null이 들어오게 강제할 것인지, 필드 누락을 허용할 것인지에 따라 달라질 수 있다고 생각합니다.!

2023-09-19 01:36 UTC, lane4company commented on src/domains/template/application/template.service.ts
> +  async createTemplate(request: CreateTemplateRequest) {
* respose 타입을 명시해주세요!
* 비즈니스 로직엔 문서 주석 도구인 jsdoc 혹은 tsdoc을 적용하면 어떨까요? 다른 개발자가 볼떄 도움이 될 것 같습니다!
 https://tsdoc.org/

2023-09-19 01:36 UTC, lane4company commented on src/domains/template/application/template.service.ts
> +    const templates = task.providerTemplates.map((providerTemplate) =>
* 위 변수들과 통일성 있도록 타입을 명시해주는게 좋을 것 같습니다.

2023-09-19 01:36 UTC, lane4company commented on src/domains/template/template.module.ts
> +  imports: [],
* import 할 모듈이 없다면 해당 코드는 제거해도 무방할 것 같습니다.

2023-09-19 01:36 UTC, lane4company commented on src/domains/template/presentation/template.controller.ts
> +  async createTemplate(@Body() request: CreateTemplateRequest) {
* respose 타입을 명시해주세요!

2023-09-19 02:53 UTC, merged