feature: 배차 성공 템플릿 생성
lane4company/lane4-notification-api pull request #6
Opened 2023-09-20 07:39 UTC by lane4-ellie

---

### PR Type ✔️

- [x] Feature - 기능 개발
- [ ] Fix - 버그 수정
- [ ] Code Style - 코드 스타일
- [ ] Refactoring - 리팩토링
- [ ] Document - 문서
- [ ] Others - 빌드, 배포 및 의존성 등 기타사항

---

### Summary(요약) ⭐

배차 성공 템플릿 생성

---

### Describe your changes(상세) 🧾

- 배차 관련 엔티티를 정의했습니다.
  - 메시지 구성에 필요한 필드만 정의하였습니다.
  - 관계로 가져올 수 있는 엔티티는 lazy relation으로 가져왔습니다.
  - 관계로 가져올 수 없는 charter 엔티티는 별도로 레포지터리 구현하여 가져왔습니다.
- Resource Finder에 대한 개념을 재정립했습니다.
  - 엔티티에 종속적 -> 태스크에 종속적
  - 따라서 하나의 Resource에는 해당 태스크에 필요한 여러 엔티티가 담길 수 있습니다.
- 태스크 지정 시 템플릿 객체가 아니라 템플릿 클래스 생성자를 정의하도록 변경했습니다.
  - 템플릿 객체를 미리 생성하여 정의해두면 같은 태스크에 대해 여러 번 요청 시 메시지 내용이 누적되는 현상을 발견하여 수정했습니다.
- 메시지 구성에 필요한 유틸리티를 생성했습니다.
  - MobileNumberMasker, UnitConverter
- 배차 성공 템플릿을 구현했습니다.
  - 원래 메시지와 동일하게 구현했습니다.
  - 추후 배차 실패 템플릿 생성 시, 타이틀 외 내용이 같다면 타이틀 생성 함수만 구현하여 사용할 수 있습니다. 
---

### Issue Number or Link 🔗

---

### Reference
- [Eager and Lazy Relations](https://orkhan.gitbook.io/typeorm/docs/eager-and-lazy-relations#lazy-relations)
---

[//]: # (PR 타이틀은 "Type: 타이틀" 형식으로 작성)

[//]: # (Summary의 경우 작업의 전반적인 내용을 함축 및 요약하여 작성)

[//]: # (Describe your changes의 경우 무슨 상황에서 왜 이러한 변경이 필요했고, 어떻게 작업햇는지 상세 기술)

[//]: # (Issue의 경우 추후 필요시 사용)

[//]: # (Reference의 경우 해당 변경점에서 중요하게 찾아본 자료가 있거나, 이해하는데 도움이 되는 내용을 포함)

2023-09-21 07:44 UTC, lane4-asher commented
[832414c](https://github.com/lane4company/lane4-notification-api/pull/6/commits/832414c0cae521221803798634b5bc8eb8c6826d)
- Lazy Loading으로 변경하신 특별한 이유가 있을까요?

---
### 공통
- 전체적으로 줄여서 쓰신 변수명 같은것들 좀 `allocationId` 처럼 풀어서 쓰는걸로 변경해주세요.

2023-09-21 07:45 UTC, lane4-asher requested changes

2023-09-21 07:45 UTC, lane4-asher commented on src/domains/resource/application/allocation.result.resource.finder.ts
> +    }
```suggestion
    if (!allocation) {
      throw new NotFoundException('배차 아이디가 유효하지 않습니다.(${allocId})');
    }
```
- 에러에서는 명시적으로 에러가 발생한 원인이 되는 정보들을 추가적으로 적어주시면 좋습니다.

2023-09-21 07:45 UTC, lane4-asher commented on src/domains/resource/resource.module.ts
- 도메인별로 모듈을 분리하고 ResourceModule에서 다른 모듈을 참조하는식으로 변경하는게 좋을것 같습니다.

2023-09-21 07:59 UTC, lane4-ellie commented
> [832414c](https://github.com/lane4company/lane4-notification-api/pull/6/commits/832414c0cae521221803798634b5bc8eb8c6826d)
> 
> * Lazy Loading으로 변경하신 특별한 이유가 있을까요?
> 
> ### 공통
> * 전체적으로 줄여서 쓰신 변수명 같은것들 좀 `allocationId` 처럼 풀어서 쓰는걸로 변경해주세요.

불필요한 로딩이 생길 수 있다고 판단했습니다. 
예를 들면 A라는 태스크에서 CallRequest는 필요하지만 ServiceUser는 필요하지 않고, 
B 태스크에서는 CallRequest와 ServiceUser가 모두 필요하다고 가정할 때 
Eager loading 시 A 태스크에 대한 리소스를 찾을 때 불필요하게 ServiceUser도 같이 조회되기 때문에 불필요하다고 생각했습니다.!

변수명 모두 변경하겠습니다.

2023-09-21 08:00 UTC, lane4-ellie commented
@lane4-asher 
> > [832414c](https://github.com/lane4company/lane4-notification-api/pull/6/commits/832414c0cae521221803798634b5bc8eb8c6826d)
> > 
> > * Lazy Loading으로 변경하신 특별한 이유가 있을까요?
> > 
> > ### 공통
> > 
> > * 전체적으로 줄여서 쓰신 변수명 같은것들 좀 `allocationId` 처럼 풀어서 쓰는걸로 변경해주세요.
> 
> 불필요한 로딩이 생길 수 있다고 판단했습니다. 예를 들면 A라는 태스크에서 CallRequest는 필요하지만 ServiceUser는 필요하지 않고, B 태스크에서는 CallRequest와 ServiceUser가 모두 필요하다고 가정할 때 Eager loading 시 A 태스크에 대한 리소스를 찾을 때 불필요하게 ServiceUser도 같이 조회되기 때문에 불필요하다고 생각했습니다.!
> 
> 변수명 모두 변경하겠습니다.

2023-09-21 08:05 UTC, lane4-ellie commented on src/domains/resource/resource.module.ts
한 리소스에서 여러 엔티티를 가질 수 있어서 리소스 파인더, 리소스 클래스를 어디 놔둘지가 좀 애매했습니다.
각 태스크에서 keyIndex에 해당하는 엔티티 도메인에 리소스 파인더, 리소스 클래스를 구현하면 될까요?

2023-09-21 23:18 UTC, lane4-ellie commented on src/domains/resource/resource.module.ts
리소스 파인더, 리소스 클래스는 그대로 Resource 라는 도메인에 두고 
Repository를 가지는 모듈을 도메인별로 생성한 뒤 ResourceModule에서 참조하는 식으로 변경하겠습니다.!

2023-09-25 07:08 UTC, lane4-ellie commented
하나의 PR이 너무 커져서 작은 단위로 쪼개어 PR 올리도록 하겠습니다.

2023-09-25 07:08 UTC, closed without merging